### ISSUE TITLE
Swerve modules not properly turning

### ISSUE THREAD

**Issue by NotSimon5673** [FRC-1721/1721-Crescendo#13]
Bug with optimization. Occasionally, when the joystick tells the robot to move in the opposite direction of its current trajectory, a swerve optimization that is supposed to drive the wheels in the opposite direction (as opposed to rotating the wheel a full π radians) fails causing the robot to keep going in it's current direction. I'm pretty sure that this optimization takes effect even when not rotating a full 1/2 rev. Causing lot's of emotional trauma in our drivers

**Comment by Kredcool** [comment]
This was determined to be a mechanic issue with the bot not turning fast enough
